version: '3.7'

services:
  httpd-app:
    image: httpd:latest
    container_name: httpd-app
    ports:
      - "8080:80"  # Mapping port 80 inside the container to port 8080 on the host

  jenkins-app:
    image: jenkins/jenkins:lts
    container_name: jenkins-app
    ports:
      - "8081:8080"  # Mapping Jenkins' port 8080 inside the container to port 8081 on the host

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"  # Mapping port 3306 inside the container to port 3306 on the host
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
